blog_url: http://blog.geoserver.org
jira_url: https://osgeo-org.atlassian.net/projects/GEOS
conf_url: http://old.geoserver.org
wiki_url: https://github.com/geoserver/geoserver/wiki
git_url: https://github.com/geoserver/geoserver
sf_url: http://sourceforge.net/projects/geoserver
nightly_url: http://ares.boundlessgeo.com/geoserver
docs_url: http://docs.geoserver.org

stable_version: 2.9.1
stable_branch: 2.9.x
maintain_version: 2.8.5
maintain_branch: 2.8.x
dev_version: 2.10-M0
dev_branch: 2.10.x
