blog_url: http://blog.geoserver.org
jira_url: http://jira.codehaus.org/browse/GEOS
conf_url: http://old.geoserver.org
wiki_url: https://github.com/geoserver/geoserver/wiki
git_url: https://github.com/geoserver/geoserver
sf_url: http://sourceforge.net/projects/geoserver
nightly_url: http://ares.boundlessgeo.com/geoserver
docs_url: http://docs.geoserver.org

stable_version: 2.5.2
stable_branch: 2.5.x
maintain_version: 2.4.7
maintain_branch: 2.4.x
dev_version: 
dev_branch: 2.6.x
